language: node_js
node_js:
  - 16

dist: bionic
sudo: required

notifications:
  email:
    recipients:
      - yongshan.yeoh@ncs.com.sg
    on_success: always
    on_failure: always
branches:
  only:
   - development
before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --base-href https://yongshanyeoh.github.io/bitcoin-order-app/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/bitcoin
  edge: true
  on:
    branch: development